Repository zzub-zzub-bak-sa/frontend, pull requests merged in 2024-02, with the labels that each got.

#23 [#22] 마이페이지 및 관련 페이지 구현
  src/assets/icons/IcTrash.jsx
  src/components/MyPageScreen/EditNicknameBottomSheet.jsx
  src/components/base/modal/YesNoModal.jsx
  src/components/layout/Header.jsx
  src/navigations/StackNavigation.jsx
  src/pages/GalleryScreen.jsx
  src/pages/MyPageScreen.jsx
  src/pages/PolicyScreen.jsx
  src/pages/TrashBinScreen.jsx
Labels: ✨ Feature

#30 [#27] 콘텐츠 상세 UI 보완 및 컴포넌트 연결
  App.jsx
  src/components/ContentScreen/CancelOrNotModal.jsx
  src/components/ContentScreen/ContentDeleteModal.jsx
  src/components/ContentScreen/DeleteOrNotModal.jsx
  src/components/ContentScreen/TagEditBottomSheet.jsx
  src/components/ContentScreen/TagEditSelectBottomSheet.jsx
  src/components/base/InputWithTag.jsx
  src/components/base/Tags.jsx
  src/components/base/Toast.jsx
  src/components/share/Create/ChangeImage.jsx
  src/components/share/Create/CreateFolder.jsx
  src/pages/ContentScreen.jsx
  src/pages/GalleryScreen.jsx
  src/utils/showSuccessToast.js
  yarn.lock
Labels: ✨ Feature

#32 [#29] 갤러리 페이지 및 휴지통 페이지 구현
  src/components/GalleryScreen/CancelOrNotModal.jsx
  src/components/base/Button.jsx
  src/components/base/modal/SelectBottomSheet.jsx
  src/pages/GalleryScreen.jsx
  src/pages/TrashBinScreen.jsx
Labels: ✨ Feature

#33 [#31] 링크 추가 컴포넌트 연결
  src/assets/icons/folders/IcCakeFolder.jsx
  src/assets/icons/folders/IcFolderFolder.jsx
  src/components/ContentScreen/TagEditBottomSheet.jsx
  src/components/HomeScreen/AddLinkBottomSheet.jsx
  src/components/base/Card.jsx
  src/components/base/SearchInput.jsx
  src/components/base/modal/CommonBottomSheet.jsx
  src/components/share/AddLInkBottomSheets/AddTagBottomSheet.jsx
  src/components/share/AddLInkBottomSheets/AddToFolderBottomSheet.jsx
  src/components/share/AddTagBottomSheets/AddTagBottomSheets.jsx
  src/components/share/Create/ChangeImage.jsx
  src/components/share/Create/CreateFolder.jsx
  src/components/share/Default.jsx
  src/components/share/Search/NoSearchResult.jsx
  src/components/share/SelectFolderBottomSheets.jsx
  src/pages/ContentScreen.jsx
  src/pages/HomeScreen.jsx
Labels: 🐛 BugFix, ✨ Feature

#35 [#34] 로그인, 회원가입 api 연결
  src/api/instance.js
  src/pages/HomeScreen.jsx
  src/pages/MyPageScreen.jsx
  src/store/store.jsx
  yarn.lock
Labels: 🔌 API

#38 [#37] 폴더 CRUD 관련 API 연결
  src/api/apis/folders.js
  src/api/service.js
  src/components/ContentScreen/TagEditSelectBottomSheet.jsx
  src/components/HomeScreen/EditBottomSheet.jsx
  src/components/HomeScreen/Folder.jsx
  src/components/HomeScreen/FolderList.jsx
  src/components/HomeScreen/SearchBox.jsx
  src/components/base/modal/CommonShortBottomSheet.jsx
  src/components/share/Create/ChangeImage.jsx
  src/components/share/Create/CreateFolder.jsx
  src/pages/GalleryScreen.jsx
  src/pages/HomeScreen.jsx
  src/pages/TrashBinScreen.jsx
  src/store/.empty
  src/store/store.jsx
  yarn.lock
Labels: 🔌 API
