Repository zzub-zzub-bak-sa/frontend, pull requests merged in 2024-01, with the labels that each got.

#3 [#1] 기본 환경 세팅
  .eslintrc.js
  .gitignore
  .prettierrc.js
  App.js
  app.json
  babel.config.js
  index.d.ts
  package-lock.json
  package.json
  postcss.config.cjs
  src/api/.empty
  src/assets/adaptive-icon.png
  src/assets/favicon.png
  src/assets/icon.png
  src/assets/splash.png
  src/components/.empty
  src/components/base/.empty
  src/pages/.empty
  src/store/.empty
  src/styles/.empty
  yarn.lock
Labels: ⚙️ Chore

#6 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/작업-제목.md
Labels: ⚙️ Chore

#9 [#4] Root Navigator 구현
  App.js
  package.json
  src/navigations/BottomTabNavigation.js
  src/navigations/StackNavigation.js
  src/pages/.empty
  src/pages/HomeScreen.js
  yarn.lock
Labels: ⚙️ Chore, ✨ Feature

#11 [#10] 반응형 width, height 및 기본 폰트 단위 설정
  package-lock.json
  src/components/.empty
  src/constants/constants.js
  src/utils/font.js
  src/utils/size.js
  yarn.lock
Labels: ⚙️ Chore

#13 [#7] 공통 컴포넌트 구현
  .eslintrc.js
  App.jsx
  package-lock.json
  package.json
  src/components/base/.empty
  src/components/base/Button.jsx
  src/components/base/Card.jsx
  src/components/base/Chip.jsx
  src/components/base/InputField.jsx
Labels: ✨ Feature

#12 [#8] 공통 Modal, BottomSheet 컴포넌트 구현
  App.js
  App.jsx
  package.json
  src/components/base/modal/CommonBottomSheet.jsx
  src/components/base/modal/CommonModal.jsx
  yarn.lock
Labels: ✨ Feature

#17 [#15] 커스텀 스타일 적용
  App.jsx
  package-lock.json
  package.json
  src/assets/fonts/SUIT-Bold.ttf
  src/assets/fonts/SUIT-ExtraBold.ttf
  src/assets/fonts/SUIT-Medium.ttf
  src/assets/fonts/SUIT-SemiBold.ttf
  src/assets/images/logo-frame.png
  src/assets/images/logo-text.png
  src/assets/images/logo.png
  src/components/layout/Layout.jsx
  src/pages/HomeScreen.js
  src/styles/.empty
  src/styles/colors.js
  src/styles/fonts.js
  yarn.lock
Labels: ⚙️ Chore

#18 [#16] 디자인 기반 CommonBottomSheet 수정
  metro.config.js
  package.json
  src/assets/images/ic_back.svg
  src/assets/images/ic_clear.svg
  src/components/base/modal/CommonBottomSheet.jsx
  yarn.lock
Labels: ✨ Feature

#19 [#14] 디자인에 따라 공통 컴포넌트 수정
  App.jsx
  app.json
  package.json
  src/assets/icons/Check.jsx
  src/assets/icons/IcClear.jsx
  src/components/base/Button.jsx
  src/components/base/Card.jsx
  src/components/base/Chip.jsx
  src/components/base/InputField.jsx
  src/components/base/SearchInput.jsx
  src/components/base/Tags.jsx
  src/components/layout/Layout.jsx
  src/pages/HomeScreen.js
  src/utils/size.js
  yarn.lock
Labels: ✨ Feature

#21 [#20] SVG import 방식 수정
  metro.config.js
  package.json
  src/assets/icons/IcBack.jsx
  src/assets/images/ic_back.svg
  src/assets/images/ic_clear.svg
  src/components/base/modal/CommonBottomSheet.jsx
  src/navigations/StackNavigation.js
Labels: ⚙️ Chore, ✨ Feature
